trigger:
- '*'

pool:
  vmImage: 'windows-latest'

 
stages:
- stage: BuildStage1
  jobs:
  - job: Build1
    steps:
    - checkout: self

    - script: |
        # Compile the first C++ code using make
        make
      displayName: 'Build C++ Program 1'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/binaries1.zip'
        replaceExistingArchive: true
      displayName: 'Create Zip Archive'

    - task: PublishBuildArtifacts@1

      inputs:

        PathtoPublish: '$(Build.ArtifactStagingDirectory)'

        ArtifactName: 'binaries'

        publishLocation: 'Container'

      displayName: 'Publish Artifact'

 

